name: Test

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run : yarn install
      shell: bash
    - run : yarn install --frozen-lockfile
      shell: bash
    - run : yarn build
      shell: bash
